// synthqa.config.ts
//
// Controls whether each test runs authenticated (logged in) or
// unauthenticated (fresh browser with no session).
//
//   requires_auth: true  → uses ../fixtures (auto-login before test)
//   requires_auth: false → uses @playwright/test (starts logged out)
//
// Edit this file locally to override the defaults generated by SynthQA.
// You do NOT need to edit the spec files themselves.

export const testConfig: Record<string, { requires_auth: boolean }> = {
  // Browser back-button after successful login re-exposes the login form and allows resubmission without re-authentication challenge
  "dbadea32-cac7-4c57-8975-9b101b489553": { requires_auth: false },
  // Successful Login with Email Persists Authenticated Session Across Page Refresh
  "1ca59502-c5ca-4852-bd2c-3c9fa3474449": { requires_auth: false },
  // Successful Login with Username (Non-Email) Routes to Correct Role-Based Dashboard
  "d4c65ddd-8f80-44ec-a650-4214b8a888d7": { requires_auth: false },
  // Logout After Login Destroys Session and Prevents Back-Button Access to Protected Pages
  "600aa6c6-ff8f-4df9-909e-d6d9c9622b7e": { requires_auth: false },
  // Re-Login After Logout With Same Credentials Succeeds Without Requiring Page Reload
  "64e0bda5-ecdd-429d-b9eb-c30480aa8cb0": { requires_auth: false },
  // Login with Email Containing Uppercase Letters Authenticates Successfully (Case-Insensitive Email Matching)
  "c39f659a-09e5-497d-a297-cbc1bedbb637": { requires_auth: false },
  // Login form submitted with whitespace-only credentials does not authenticate and shows field-level validation errors
  "96c61744-556b-4354-bc9d-ffb32c00e7bf": { requires_auth: false },
  // Re-submission of login form after failed authentication attempt without changing credentials does not cause silent failure or UI freeze
  "0170af81-cecf-46a7-96ea-bf590b6a0840": { requires_auth: false },
  // Authentication API returning HTTP 500 displays a user-facing error message instead of silently failing or exposing a stack trace
  "f83fcf10-02d9-4886-86b4-48495e82767b": { requires_auth: true },
  // Double-click on login submit button does not dispatch two authentication requests causing duplicate session creation or account lockout acceleration
  "34b0bc99-bf2f-42c9-839a-c8eec14d1b6c": { requires_auth: false },
  // Login field content pasted from clipboard bypasses format validation and is correctly rejected when pasted value is malformed
  "924cbb5a-2662-40e3-89e4-a7ab752b5c47": { requires_auth: false },
  // Login with email containing plus-tag and subdomain (RFC-valid but often rejected by naive validators)
  "43749226-b136-4635-b65e-64c98d6d00f3": { requires_auth: false },
  // Login field autofilled with stale browser-cached credentials then silently overwritten — stale session submitted
  "48b73ca9-053b-4e6f-b174-73be7b4e3bfb": { requires_auth: false },
  // Rapid double-submit of login form creates duplicate concurrent authentication requests — race condition producing two sessions
  "a6835aa2-3ceb-414d-9f86-713a386967aa": { requires_auth: false },
  // Username field populated with Arabic RTL text renders and submits correctly in a LTR-oriented form layout
  "f1259933-2ad1-4b8b-ac56-05a89d731111": { requires_auth: true },
};
