// synthqa.config.ts
//
// Controls whether each test runs authenticated (logged in) or
// unauthenticated (fresh browser with no session).
//
//   requires_auth: true  → uses ../fixtures (auto-login before test)
//   requires_auth: false → uses @playwright/test (starts logged out)
//
// Edit this file locally to override the defaults generated by SynthQA.
// You do NOT need to edit the spec files themselves.

export const testConfig: Record<string, { requires_auth: boolean }> = {
  // Successful Login with Email and Password Redirects to Dashboard
  "f99c62d9-175f-438a-bd19-16fc5ceed9ea": { requires_auth: false },
  // Successful Login with Username and Password Redirects to Dashboard
  "f76e1a54-0966-4ce3-abb1-660e4a05519c": { requires_auth: false },
  // Remember Me Checkbox Persists Authenticated Session Across Browser Restart
  "fcc2f78e-5b35-4450-bbaa-e09ddc55e92b": { requires_auth: true },
  // Login Prevents Duplicate Submission While Loading State Is Active
  "ba44c111-8b1b-4a0a-9020-d6b09f109817": { requires_auth: false },
  // Successful Login Redirects User to Last Intended Page (Deep Link Redirect)
  "3b69de7f-7c03-4ae0-80ff-8bf2ef871378": { requires_auth: false },
  // Submit Login Form With All Fields Empty Shows Required Field Errors
  "d5417e84-176a-4f0e-8210-ff718413ef33": { requires_auth: false },
  // Login With Malformed Email Format Displays Inline Format Validation Error
  "113608dd-45fe-4d95-9bfd-7ba03b3b70c7": { requires_auth: false },
  // Login With Correct Email But Wrong Password Shows Generic Error Without Revealing Account Existence
  "b97b868c-cdb0-44b0-aa11-227692d1d302": { requires_auth: false },
  // Submit Button Is Disabled During Loading State to Prevent Duplicate Submissions
  "d1d5142b-dc00-45a9-a9b8-5402b4f817a1": { requires_auth: true },
  // Login With Excessively Long Password Value Displays Appropriate Validation Error
  "2509d089-d003-4e06-b643-4623736460d5": { requires_auth: false },
};
